---
name: Continuous Deployment

on: 
  push:
    branches:
      - main
      - cicd
  pull_request: []

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: | 
          npm install
          npm run test
          npm run lint

  deploy-firebase:
    name: Deploy to Firebase
    runs-on: ubuntu-22.04
    needs: [test_and_lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        run: echo "Deploy to firebase"